version: '3.8'
services:
  checkvalidator:
    build: .
    container_name: checkvalidator
    volumes:
      - /var/log/validator:/var/log/validator  # To persist log files on the host
      - /root/githubtest/websiteinterrogate/composedeploy/validatorchecker/screenshots:/root/githubtest/websiteinterrogate/composedeploy/validatorchecker/screenshots #used for testing
      
    environment:
      - NODE_ENV=production
      - GUILD_SITE_SENTNL=https://wax.sengine.co/guilds/oneinacilian
      - GUILD_SITE_LEDGERWISE_TESTNET=https://nodestatus.ledgerwise.io/wax-test/producer/oneinacilian
      - GUILD_SITE_LEDGERWISE_MAINNET=https://nodestatus.ledgerwise.io/wax/producer/oneinacilian
      - GUILD_SITE_VALIDATIONCORE_TESTNET=https://wax-test.validationcore.io/validations/oneinacilian
      - GUILD_SITE_VALIDATIONCORE_MAINNET=https://wax.validationcore.io/validations/oneinacilian
      - LEDGERWISE_PUSHGATEWAY=http://172.168.40.200:9091/metrics/job/wax_node_status
      - SENTNL_PUSHGATEWAY=http://172.168.40.200:9091/metrics/job/wax_sengine
      - VALIDATIONCORE_PUSHGATEWAY=http://172.168.40.200:9091/metrics/job/wax_validation
      - VALIDATIONCORE_ENABLE_SCREENSHOT=true
      - SENTNL_ENABLE_SCREENSHOT=true
      - LEDGERWISE_ENABLE_SCREENSHOT=true
      - SCREENSHOT_PATH=/root/githubtest/websiteinterrogate/composedeploy/validatorchecker/screenshots
    restart: always
